config:
  node_agent: 'docker_compose'
  deploy_template: '.sqa/docker-compose.yml'
  project_repos:
    fuji_app_repo:
      repo: 'https://github.com/EOSC-synergy/fuji'
      branch: master
      # credentials_id: fuji-github

  credentials:
      - id: userpass_sqaaas_web
        username_var: GIT_USER
        password_var: GIT_PASSWORD

sqa_criteria:
  qc_style:
    repos:
      fuji_app_repo:
        container: fuji_app_container # Allows to specify the Docker container where the given criteria assessment will take place. If using docker_compose, the value could be any of the services defined in the docker-compose.yml
        tox:
          testenv:
            - stylecheck
  qc_doc:
    repos:
      fuji_app_repo:
        container: fuji_app_container
        commands:
          - >
            echo "Success"
            printenv JPL_FUJI

environment:
  JPL_FUJI: "Hello from Jenkins workspace!"
  JPL_DOCKERPUSH: "fuji_app_container"
  JPL_IGNOREFAILURES: "defined"

timeout: 1200
