config:
  node_agent: 'docker_compose'
  deploy_template: '.sqa/docker-compose.yml'
  project_repos:
    fuji_app_repo:
      repo: 'https://github.com/EOSC-synergy/fuji'
      branch: master
#       credentials_id: fuji-github

  credentials:
      - id: userpass_sqaaas_web
        username_var: GIT_USER
        password_var: GIT_PASSWORD

sqa_criteria:
  qc_style:
    repos:
      fuji_app_repo:
        container: fuji-tester 
        tox:
          tox_file: /fuji-fuji_app_container/tox.ini
          testenv:
            - stylecheck
  qc_doc:
    repos:
      fuji_app_repo:
        container: fuji_app_container
        commands:
          - >
            echo ${JPL_FUJI}

environment:
  JPL_FUJI: "Hello from Fuji container!"
#   JPL_DOCKERPUSH: "fuji_app_container"
  JPL_DOCKERFORCEBUILD: "true"
#   JPL_IGNOREFAILURES: "true"

timeout: 1200
