config:
  credentials:
      - id: userpass_sqaaas_web
        username_var: GIT_USER
        password_var: GIT_PASSWORD

sqa_criteria:
  qc_doc:
    repos:
      fuji:
        container: node
        commands:
          - > 
            echo "Success"
