version: "3.7"

services:
  node:
    image: node
    container_name: node
    hostname: "fuji"
    volumes:
     - type: bind
       source: ./
       target: /sqaaas-web
    command: sleep infinity
