version: "3.7"

services:
  fuji_app_container:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    ports:
      - "1071:1071"        
    # image: "organization/fuji:${GIT_BRANCH}"

  # fuji-tester:
  #   image: "indigodatacloud/ci-images:python3.6"
  #   container_name: "fuji-tester"
  #   volumes:
  #    - type: bind
  #      source: ./fuji_app_repo
  #      target: /fuji-tester
